### ISSUE TITLE
Update log4j library to 2.17.1 version

### ISSUE THREAD

**Issue by morazow** [exasol/cloudwatch-adapter#59]

**Comment by kaklakariada** [comment]
Log4j 2.17.0 has a security issue: https://github.com/dependency-insights/maven/org.apache.logging.log4j%253Alog4j-api/2.17.0/security?query=org%3Aexasol

> Apache Log4j2 versions 2.0-beta7 through 2.17.0 (excluding security fix releases 2.3.2 and 2.12.4) are vulnerable to an attack where an attacker with permission to modify the logging configuration file can construct a malicious configuration using a JDBC Appender with a data source referencing a JNDI URI which can execute remote code.

This attack scenario is not relevant for the Cloudwatch Adapter because it is running in a Lambda and the attacker does not have access to the config file.

Nevertheless we will update the dependency in #57
